### ISSUE TITLE
List Box default value

### ISSUE THREAD

**Issue by aviteshchandra** [Softdiscover/Zigaform-WP-Cost-Estimator-Lite#1]
Hello. I would like to know if there is a way, by default no value is selected for the list options. Currently the first option is automatically selected from the list?

**Comment by larangin** [comment]
hello, by default select list field need an option. you want to have an option with no value. you can set the first option of the select list with no value. I mean. you can put the label "Choose an option" and put the value option to empty. and if you want to force user to choose an option. you can add required validation to that. let me know if something is not clear
