### ISSUE TITLE
Add New or Import Builder load Issue - Firefox Error: removeCss is not a Function

### ISSUE THREAD

**Issue by Jene-Maree** [Softdiscover/Zigaform-WP-Cost-Estimator-Lite#11]
Hi Guys,

I have just installed your plug-in today and it really seems like it is going to do what I need it to accept that I am having an issue with the builder. When selecting the add new or Import option the loading screen hangs and does not go away. When hiding this overlay with dev tools everything seems to function normally accept that the import functionality is not triggered (assume this error is causing that aspect). When implementing a template, however, this issue is eliminated. I just thought I would bring this to your attention. please let me know if you need any further info for debugging.

Firefox Error msg:

Uncaught TypeError: t(...).removeCss is not a function
    previewform_skin_maxwidth https://beta.bushtrails.com/wp-content/plugins/zigaform-calculator-cost-estimation-form-builder-lite/assets/backend/js/admin.min.js?ver=5.2.3:1
    setDataOptToPrevForm https://beta.bushtrails.com/wp-content/plugins/zigaform-calculator-cost-estimation-form-builder-lite/assets/backend/js/admin.min.js?ver=5.2.3:1
    loadFormToEditPanel_default https://beta.bushtrails.com/wp-content/plugins/zigaform-calculator-cost-estimation-form-builder-lite/assets/backend/js/admin.min.js?ver=5.2.3:1
    each jQuery
    loadFormToEditPanel_default https://beta.bushtrails.com/wp-content/plugins/zigaform-calculator-cost-estimation-form-builder-lite/assets/backend/js/admin.min.js?ver=5.2.3:1
    each jQuery
    loadFormToEditPanel_default https://beta.bushtrails.com/wp-content/plugins/zigaform-calculator-cost-estimation-form-builder-lite/assets/backend/js/admin.min.js?ver=5.2.3:1
    loadNewForm https://beta.bushtrails.com/wp-content/plugins/zigaform-calculator-cost-estimation-form-builder-lite/assets/backend/js/admin.min.js?ver=5.2.3:1
    <anonymous> https://beta.bushtrails.com/wp-admin/?page=zgfm_form_builder&zgfm_mod=formbuilder&zgfm_contr=forms&zgfm_action=create_uiform&opt=import:3221
    jQuery 9
        dispatch
        handle
        add
        add
        ke
        each
        each
        ke
        on
    <anonymous> https://beta.bushtrails.com/wp-content/plugins/zigaform-calculator-cost-estimation-form-builder-lite/assets/common/bootstrap/3.3.7/js/bootstrap.js?ver=5.6.1:529
    <anonymous> https://beta.bushtrails.com/wp-content/plugins/zigaform-calculator-cost-estimation-form-builder-lite/assets/common/bootstrap/3.3.7/js/bootstrap.js?ver=5.6.1:536

**Comment by larangin** [comment]
hello, could you export your form, then send me the exporting code in a txt file in order to import it and reproduce it on my side? you can send me at info@softdiscover.com
or give me the step in order to reproduce that issue on my side.

**Comment by Jene-Maree** [comment]
Hi @larangin,

Thank you for the response. this issue is not occurring in relation to a specific form but rather in relation to the Firefox browser as I have tested on chrome and it does not happen there. I have attached screenshots for your reference. When selecting either create new form options or the import option the loading screen times out and stays put due to firefox not recognizing the function RemoveCss. This does not occur when editing an existing form. Hope this helps.

![Screenshot_2021-02-22 Forms ‹ BushTrails — WordPress](https://user-images.githubusercontent.com/61537370/108672196-590b1580-74ea-11eb-82e0-729dd58bb55c.png)
![Error 1](https://user-images.githubusercontent.com/61537370/108672200-5a3c4280-74ea-11eb-8714-7cd77590a184.png)
![Screenshot_2021-02-22 Forms ‹ BushTrails — WordPress(1)](https://user-images.githubusercontent.com/61537370/108672201-5ad4d900-74ea-11eb-84aa-2d74d0d4796e.png)

**Comment by larangin** [comment]
hello, I've just tested on firefox. and that error does not appear on my side. try to test in fresh wordpress installation . also can you try on my admin demo: https://wordpress-cost-estimator.zigaform.com/get-admin-demo/
I tested and that error does not appear there.
