### ISSUE TITLE
Multiple Submit button in one form

### ISSUE THREAD

**Issue by pinky-ring** [Softdiscover/Zigaform-WP-Cost-Estimator-Lite#13]
In the Estimator form, I want to show price table at the end.
For different grade of services like, basic, deluxe, and premium.
I would like to put submit button on each service.
However, I don't see how I can differentiate those buttons...

Is there any way I can tell which button the customer clicked??

**Comment by larangin** [comment]
ok. I guess you want to show a result according to selected option in the success message. well, it can be done but it is kind of tricky. first, you have to add a hidden field. then enable calculation feature. then build the calculation logic and store the result message in a variable, then store it into the hidden field, then when the form is submitted, you will have to put the shortcode of the hidden field in the success message. I hope it is clear.

**Comment by pinky-ring** [comment]
Thank you so much larangin.
It sounds like very complicated...
Is it possible to teach me how to do it by step by step by any chance?

**Comment by pinky-ring** [comment]
I was thinking that since I'm making price table by custom html,
I can make each button with specific id.   
The problem is, I didn't know how to make the submit function.

like you said, I want to send success message and also sending email with the selected option...

**Comment by larangin** [comment]
yes, it is kind of complicated for someone who is not developer. if it helps, I made a form with that logic. here the video: https://www.youtube.com/watch?v=JGyPIiIO38I
you can see two messages are stored in two hidden inputs. then that shortcode( hidden input with custom message) is placed  into the mail message and user get the custom message in the mail notification. that shortcode can be placed into to success message and you will have your result.

**Comment by larangin** [comment]
> I was thinking that since I'm making price table by custom html,
> I can make each button with specific id.
> The problem is, I didn't know how to make the submit function.
> 
> like you said, I want to send success message and also sending email with the selected option...

as I said, there is no way to do that because when form is submitted, all form is cleaned. and replaced with success message. unless, you dont want to submit the form, and just show buttons that make hide and show results (all html), you can do that, just add a button and add additional javascript and attach the event to those button.

**Comment by pinky-ring** [comment]
Thank you again Larangin.
I will make time to watch and understand the video sometime in this week.
Whether I figure out or not, I will let you know the result.
I appreciate your help :)

**Comment by pinky-ring** [comment]
I watched video.
I add "hidden input" at my last estimation form page which is below the price tables.
I figured I need to use the code in the following page.
https://kb.softdiscover.com/docs/zigaform-wordpress-cost-estimator/events/

and.... to accomplish the mission I want, which is 
1) getting information from submit button (Which price table customer chose)
2) put the result in the email form

Please collect me if I'm not thinking right.
I need to use “zgfm.form.before_submit”callback event function to get the data and stored it in hidden input...
Am I on right track?

**Comment by larangin** [comment]
hello, 
no, you dont need the zigaform events. 
just add the code inside the calculation code, In the calculation code (javascript), just collecting information into a variable, then grab that variable and store it into the hidden field. then when form is submitted, the software itself will collect all data (hidden input included), then you will be able to use the value of that hidden input into your email notification or success message. does it make sense?

**Comment by pinky-ring** [comment]
Thank you again Larangin.
I watched video couple times... and read your message couple times....
Please tell me I'm on right track or not

What I need to do is...
1)Make code to grab which button were pushed.
For this, I use "onclick" DOM event which is...

var Grade;
var Total;
function getGrade(){
if(document.getElementById("type what submit button ID selector displayed in here").onclick))
{
Grade="Basic";
Total=BasicTotal;
} else if(document.getElementById("type what submit button ID selector displayed in here").onclick))
{
Grade="Premium";
Total=PremiumTotal;
} else if(document.getElementById("type what submit button ID selector displayed in here").onclick))
{
Grade="Deluxe";
Total=DeluxeTotal;
}

2)Then I should put this in hidden field(I make two hidden field"
 jQuery('hidden field ID').find('texarea').val(Grade);
 jQuery('hidden field ID').find('texarea').val(Total);

3)In the email tab, I can use form ID of hidden field to display.

**Comment by pinky-ring** [comment]
The estimation is not working so I think I'm not doing right...

**Comment by pinky-ring** [comment]
I changed #1 to be like this but still no success:

var Grade;
var Total;


$('submit button1's ID, submit button2's ID, submit button3's ID').click(function(){
if(this.id=="submit button1's ID")
{
Grade="Basic";
Total=BasicTotal;
} else if(this.id=="submit button2's ID")
{
Grade="Premium";
Total=PremiumTotal;
} else if(this.id=="submit button3's ID")
{
Grade="Deluxe";
Total=DeluxeTotal;
}
});

**Comment by pinky-ring** [comment]
I belive #1 code is not working right because C.Logic stop working when I made this code in the calculation.
When I comment it out, C.Logic start working again...

Is there anything you realize that I can make collection?
Thank you so much for your help in advance :)

**Comment by pinky-ring** [comment]
For the Total, I have calculation already that is working.
I display each price on the price table.
So  I'm just calling the vale.

**Comment by larangin** [comment]
ok. I mentioned you to add that into the calculation code but I see you are adding the code into the additional javascript code which you will have to create the events to capture the click buttons. 
well. this is another way to do that. i see your code is fine. 

```
var Grade;
var Total;

$('submit button1's ID, submit button2's ID, submit button3's ID').click(function(){
if(this.id=="submit button1's ID")
{
Grade="Basic";
Total=BasicTotal;
} else if(this.id=="submit button2's ID")
{
Grade="Premium";
Total=PremiumTotal;
} else if(this.id=="submit button3's ID")
{
Grade="Deluxe";
Total=DeluxeTotal;
}
});

jQuery('hidden field ID').find('texarea').val(Grade);
jQuery('hidden field ID').find('texarea').val(Total);
```

then in the mail tab, you can use the backend shortcode of that field, just copy and paste. got it?

**Comment by pinky-ring** [comment]
hmm...
I'm little bit lost... I type the code in the calculation.... should I copy that in javascript code?
![calculation-GetGrade](https://user-images.githubusercontent.com/67244939/110730618-9acbd980-81d5-11eb-9a3a-c2ed7bc24dcc.gif)

**Comment by pinky-ring** [comment]
should I copy and paste in here instead?
![additionalJava](https://user-images.githubusercontent.com/67244939/110730754-e4b4bf80-81d5-11eb-8a98-166be5d45435.jpg)

**Comment by larangin** [comment]
yes, you should add that code into the additional code because you are  defining an event: 
```
$('submit button1's ID, submit button2's ID, submit button3's ID').click(function(){
...
```
in the calculation, you dont need to define an jquery event but you can do it as well. it is not optimum but it works.

**Comment by pinky-ring** [comment]
Can I ask how to do the best way?
I'm not sure how to do it in the calculation.

I really appreciate your patience :)

**Comment by pinky-ring** [comment]
I copy and paste following code to the additional javascript part.
However it seems not working...
when I push button, it goes through but hidden input doesn't show any value....


var Grade;
var Total;

$('submit button1's ID, submit button2's ID, submit button3's ID').click(function(){
if(this.id=="submit button1's ID")
{
Grade="Basic";
Total=BasicTotal;
} else if(this.id=="submit button2's ID")
{
Grade="Premium";
Total=PremiumTotal;
} else if(this.id=="submit button3's ID")
{
Grade="Deluxe";
Total=DeluxeTotal;
}
});

jQuery('hidden field ID').find('texarea').val(Grade);
jQuery('hidden field ID').find('texarea').val(Total);
 This is email setting
![emailsetting](https://user-images.githubusercontent.com/67244939/111005276-5d835b00-833f-11eb-92bd-f275d9784cf2.gif)

When I recieve email, no value showes
![recivedemail](https://user-images.githubusercontent.com/67244939/111005288-62480f00-833f-11eb-8dc6-7a86a8a49578.jpg)

**Comment by larangin** [comment]
definitely your code is not working well. send me access or send exporting code of the form to my mail info@softdiscover.com in order to take a look. regards

**Comment by pinky-ring** [comment]
Thank you so much Larangin!
I send email to the email address.

**Comment by larangin** [comment]
hello, yes, I received your email and checked. and replied you.

**Comment by larangin** [comment]
since there is not response. this issue is closed
