### ISSUE TITLE
Range slider - formatting issue

### ISSUE THREAD

**Issue by Matthieu971** [Softdiscover/Zigaform-WP-Cost-Estimator-Lite#14]
<img width="619" alt="Capture d’écran 2021-03-12 à 11 36 10" src="https://user-images.githubusercontent.com/80519019/110928479-3751c100-8327-11eb-9df3-afebbd36083c.png">

Hi, on this picture I would like to improve the formatting of the numbers in black font below the range slider (including the total). Where can I customize this within Zigaform please ? 

Thank you !

Matthieu

**Comment by larangin** [comment]
hello, you can do that via css.  you can do it globally or by field. here a video tutorial how to do it by field: https://kb.softdiscover.com/knowledgebase/customize-fields-via-css/

**Comment by larangin** [comment]
since there is no response. this issue is closed.
