### ISSUE TITLE
Different email content from one form

### ISSUE THREAD

**Issue by pinky-ring** [Softdiscover/Zigaform-WP-Cost-Estimator-Lite#15]
Hello Again.
I'm just wondering that there is a way to make different content mail to the customer based on what service they chose.
I want to get regular house owner clients and commercial property owner clients and have two different content mail to be sent...
I believe zigaform doesn't have the feature... or is there one?

**Comment by larangin** [comment]
hello again, yes, as I explained on previous, you can do that via hidden field, you build your custom result when customer is filling the form, then the custom result is store into the hidden field, you just put the shortcode of that hidden field into mail notification and that's it. got it? here I did some kind of similar: https://kb.softdiscover.com/docs/zigaform-wordpress-cost-estimator/examples/demo-5/
