### ISSUE TITLE
potential bug in conditional fields

### ISSUE THREAD

**Issue by ehrenberg** [Softdiscover/Zigaform-WP-Cost-Estimator-Lite#16]
Hello there,
I would like to create a form for a customer that has conditional fields between the step wizard pages.
now i have seen in the demo that there seems to be an error in the conditional logic under c-logic. "undefined" is always shown for the values. Is that a general mistake or only in the admin demo?
can i use zigaform to create conditional fields between step wizard pages?

**Comment by larangin** [comment]
hello, could you send the url of the demo? and answering to your question. yes, the conditional logic is for the whole page (wizard included)

**Comment by ehrenberg** [comment]
I've tested with a 10min Mail Account and I don't have the email address anymore. And actual https://wordpress-form-builder.zigaform.com/get-admin-demo/ isnt sending any mails now.
You can't test it without the Demo-Url?

**Comment by larangin** [comment]
you can test it download the free version: https://wordpress.org/plugins/zigaform-calculator-cost-estimation-form-builder-lite/
check it out and let me know

**Comment by larangin** [comment]
since there is no response. this issue is closed.
