### ISSUE TITLE
Dynamic RadioButton - Enable Quantity

### ISSUE THREAD

**Issue by lsoto6509** [Softdiscover/Zigaform-WP-Cost-Estimator-Lite#17]
I installed the free version of the calculator for WordPress.

I added a Dynamic RadioButton and Enabled Quantity. When I go to Calculations, I cannot find a variable that contains the quantity. How can I use it in the calculation?

Is it possible to display a validation message if the quantity is greater than the maximum allowed?

**Comment by larangin** [comment]
1)  for dynamic checkbox field, you can get the Field price or Option price. in the calculation. if you want to get the quantity, just add a conditional like this. 

```
var quantityOption1=0;
if(fld_ui1pp0rgikl_optIsChecked_0){
  var pricePerUnit=4;
  quantityOption1=fld_ui1pp0rgikl_optprice_0/pricePerUnit;
}
```

in summary, you check if the option is checked, then you divide option price by price per unit which is a constant that you defined on field options. 

2) no, that kind of validation is not available. you would need to add custom javascript code to do that
