### ISSUE TITLE
radiobutton when hidden with Conditional Logic does not send value to custom math calculation

### ISSUE THREAD

**Issue by damirkonjevod** [Softdiscover/Zigaform-WP-Cost-Estimator-Lite#18]
1. I've set up conditional logic on a radiobutton control to show it only if another checkbox control is checked. 
2. The radiobutton control has a "default" checked option
3. I've added an optional variable under custom math calculation (which is ON) where I'm using the VALUE of the selected option  of that radiobutton as NUMERIC.
4. the optional variable value is then displayed in custom HTML control on the form.
5.  I saved the form
6. I clicked Refresh & Clean Form option
7. on preview screen, when I don't select the checkbox to display the radiobutton control, the optional variable is not returning a result
8. when I do select that checkbox and make the radiobutton control visible, the result from the optional variable is seen in the custom HTML control.
9. if I hide the radiobutton again (regardless of changing the option in the radiobutton or not), the optioanl variable is not showing the result.

I believe this is a bug
what should I be using to circumvent this issue?

**Comment by larangin** [comment]
hello, I already replied you by mail. 
1. here a tutorial video. that's basic: https://kb.softdiscover.com/docs/zigaform-wordpress-cost-estimator/features/conditional-logic/
2. yes, you can set a default checked option
4. yes, the variable can be displayed on the form. 

as I mentioned in the mail, your custom code generated an error. many variables were not defined and if there is an error in the code, it will break the whole form.

**Comment by damirkonjevod** [comment]
Hello, thank you for your anwer, but that is not relevant to the issue I'm describing. I think you think it is a feature, not a bug :)
so:
1. I know of the given video, and it is the basic as you've said. I didn't have issues with setting up conditional logic
2. I didn't have issue with setting up default checked option
3. I didn't have issue with displaying variable value on the form

I have issue with retrieving **hidden** radio button control option value. The custom code you are referring to was for another issue that you've successfully helped me resolve. The code is working fine because when the controls are shown, the value is shown in the form. When you hide some of the radiobuttons whose values are used to calculate the variable to be displayed - then there is no result. 

so this could be either bug or a feature. Question: is it by design on purpose that you do not return value/option of a hidden control in the custom code section? It seems to me you do, since based on that video link when you submit the form, only visible fields are sent in the submission, so it may be that logic...
