### ISSUE TITLE
CheckBox fiels - get an array

### ISSUE THREAD

**Issue by DiAnnaDan** [Softdiscover/Zigaform-WP-Cost-Estimator-Lite#19]
How can i define var that is an array of checkbox options value (and not price)?

**Comment by larangin** [comment]
hello, what you want is to store the checkbox options into a var? if so, you can do that via javascript, get the field element and get checkbox options. there are a lot info out there. here one: https://stackoverflow.com/questions/11292778/use-jquery-to-get-values-of-selected-checkboxes
