### ISSUE TITLE
Validation Submit

### ISSUE THREAD

**Issue by Lukym81** [Softdiscover/Zigaform-WP-Cost-Estimator-Lite#2]
How can I validate two inputs if they are the same before pressing the send button

**Comment by larangin** [comment]
hello, you can do that with zigaform events: 
https://kb.softdiscover.com/knowledgebase/zigaform-events/

you can use the validation callback event:
`jQuery( document ).ready(function($) {
  $(document).bind("zgfm.form.wizbtn_additional_validation", function(e,callback) {
    if(true){
      callback({
      is_valid:true
      });
    }else{
      callback({
      is_valid:false
      });
    }
  });
});`

you would need to add that as additional javascript. go to Global settings-> additional-> then add the javascript code.

**Comment by larangin** [comment]
since there is no replies. I will close this issue
