### ISSUE TITLE
howto send the value of a calculated variable in the mail to customer/admin

### ISSUE THREAD

**Issue by adt3030** [Softdiscover/Zigaform-WP-Cost-Estimator-Lite#21]
Hi,
Is there anyway to write an optional variable value in the mail to admin/customer?

**Comment by larangin** [comment]
yes, once calculation variables are created, it can be used both frontend or backend. so edit the form-> go to Option button, then Variables, then a modal will appear, then you can use all shortcodes that appear under Backend tab. here some ref: https://youtu.be/keBrsqvOvLg?si=j_CrP2ILRn2DBLzI&t=248
