### ISSUE TITLE
sync two field with code

### ISSUE THREAD

**Issue by carlkrsh** [Softdiscover/Zigaform-WP-Cost-Estimator-Lite#3]
Hello. i wrote this code and its working. but i need to change "fld_ui3smnvemox_value" to "fld_uie1fx51eri_price" in that if statement. 

if(fld_uie1fx51eri_optIsChecked_y4neq || fld_uie1fx51eri_optIsChecked_y7lkz){ 
  var pool_fee = fld_uie1fx51eri_price ;
  
} else {
  var pool_fee = fld_ui3smnvemox_value;
}

then i wrote this one to get the element data and replace it but its not working. 

var b = document.getElementById("rockfm_uie1fx51eri").getElementsByTagName("li");

for (let i = 0; i < b.length; i++) {
  b[i].addEventListener("click", function() {  
    console.log(b[i].textContent);
  });
};

can you help me?
i need to sync a dropdown select list with an input field.. that if user select a value from dropdown, so input must show the value of dropdown that is selected.. but else , if inputed directly in that input field.. it will use the value of input field. and change the select list option to else.

**Comment by larangin** [comment]
hello, sorry for late response. yes, you can do that adding javascript in  calculation. 

1) first capture the value of dropdown
2) then get that value and add it to input

at reverse:
1) add a keyup event to capture text from the input: 
https://www.w3schools.com/jquery/event_keyup.asp

2) then update it to dropdown list. but remember change the dropdown list to default style.

**Comment by larangin** [comment]
since there is no replies. I will close this issue
