### ISSUE TITLE
cost calculation doesnt work....

### ISSUE THREAD

**Issue by pinky-ring** [Softdiscover/Zigaform-WP-Cost-Estimator-Lite#4]
I'm trying to figure out how to estimate the cost for window cleaning...
![window cleaning zigaform](https://user-images.githubusercontent.com/67244939/85639566-f3eedf80-b63d-11ea-8ad9-30be2c6b6c0c.jpg)

So I made two radio button choices
1)property type
2)side of windows(both side or only one side)

I try to make the true and false calculation 
and for commercial property, I assigned the price to be 0
for residential property, I assigned the price to be 1

and for one side only cleaning, I assigned the price to be 0
for both sides, I assigned the price to be 1

this is my calculation I tried...
I tried many other calculations but nothing seems to work....
is there anyone who can help me out?

__________________________________________________________________________________
var propertyType=fld_uie3k7dqnrn_price;  //I want the form to know it is commerical or residential 
var side=fld_uikb2uvxfy8_price;  //I want the form to know that is for one side or both sides
var subTotal=0;
var total=0;
var comWinSmall=2; //commercial properties small window price per side
var comWinRegular=3;  //commercial properties Regular window price per side
var comWinLarge=5;  //commercial properties Large window price per side
var resWinSmall=3;  //residential properties small window price per side
var resWinRegular=5; //residential properties small window price per side
var resWinLarge=8; //residential properties small window price per side

/* fld_uiaa2cr5irs_value is small window quantity
fld_uiif03bzjml_value is regular window quantity
fld_uiwb01xinft_value is large window quantity*/

if (propertyType=0){
  subTotal=(comWinSmall*fld_uiaa2cr5irs_value)+(comWinRegular*fld_uiif03bzjml_value)+(comWinLarge*fld_uiwb01xinft_value);
	total=subTotal;
	if(side=1){
    total=subTotal*2;
  }
}else if (propertyType=1){
  subTotal=(resWinSmall*fld_uiaa2cr5irs_value)+(resWinRegular*fld_uiif03bzjml_value)+(resWinLarge*fld_uiwb01xinft_value);
    total=subTotal;
	if(side=1){
    total=subTotal*2;
  }
  }else{
  total=0;
}

  return total;

**Comment by pinky-ring** [comment]
I also tried this calculation but this one makes form not showing anything on summary anymore...

--------------------------------------------------------------------------------------------------------------------------
if (propertyType=0 && side=0){
  subTotal=(comWinSmall*fld_uiaa2cr5irs_value)+(comWinRegular*fld_uiif03bzjml_value)+(comWinLarge*fld_uiwb01xinft_value);
  total=subTotal;
  }else if(propertyType=0 && side=1){
  subTotal=(comWinSmall*fld_uiaa2cr5irs_value)+(comWinRegular*fld_uiif03bzjml_value)+(comWinLarge*fld_uiwb01xinft_value);
  total=subTotal*2;
}
else if (propertyType=1 && side=0){
  subTotal=(resWinSmall*fld_uiaa2cr5irs_value)+(resWinRegular*fld_uiif03bzjml_value)+(resWinLarge*fld_uiwb01xinft_value);
  total=subTotal;
}
else if (propertyType=1 && side=1){
  subTotal=(resWinSmall*fld_uiaa2cr5irs_value)+(resWinRegular*fld_uiif03bzjml_value)+(resWinLarge*fld_uiwb01xinft_value);
    total=subTotal*2;
}

  return total;

**Comment by pinky-ring** [comment]
I decided to use custom html instead of the radio button field.
To make my own radio button with custom id 　
Now my math is working !! 🥳🥳🥳

But I need to fix one more bug....🤔
The total amount doesn't change automatically after switching the radio button.  it will change after I change the window quantity...

Is anyone know the script to auto-refresh after switching the radio button choice??

**Comment by larangin** [comment]
hello, sorry for late response. try to use console.log in order to track values in the calculation code: 
https://www.w3schools.com/js/js_output.asp

did you figure it out? let me know how it goes

**Comment by larangin** [comment]
since there is no replies. I will close this issue
