### ISSUE TITLE
I can't see my Forms

### ISSUE THREAD

**Issue by CordialGit** [Softdiscover/Zigaform-WP-Cost-Estimator-Lite#5]
Hello Sir,
I have forms on my site, but I can't see them. On the List form Page, the forms are listed, but it doesn't show them to me, and this means I can't edit them. See the screenshot-- https://prntscr.com/uhehvj

Please, How can I fix this?

Regards
![No Zigaforms](https://user-images.githubusercontent.com/71306712/93165437-f4b28180-f713-11ea-86c6-1cdc6df45bb2.png)

**Comment by larangin** [comment]
hello, just upgrade to latest version. let me know how it goes

**Comment by larangin** [comment]
since there is no replies. I will close this issue
