### ISSUE TITLE
how to build a loan payment

### ISSUE THREAD

**Issue by robertozevinho** [Softdiscover/Zigaform-WP-Cost-Estimator-Lite#6]
here just asking how to build a loan payment calculator

**Comment by robertozevinho** [comment]
...

**Comment by robertozevinho** [comment]
test

**Comment by robertozevinho** [comment]
test

**Comment by larangin** [comment]
here the documentation how to build a loan payment calculator:
https://kb.softdiscover.com/docs/zigaform-wordpress-cost-estimator/create-form/math-calculation/

**Comment by robertozevinho** [comment]
ok. thanks
