### ISSUE TITLE
Repeat form for final total, possible?

### ISSUE THREAD

**Issue by mikeb1028** [Softdiscover/Zigaform-WP-Cost-Estimator-Lite#9]
I have a cost calculation form built and find this package very capable of performing complex calculations.  However, I need to know if it is capable of this...

My form calculates the cost of an item, including labor, materials and options based on dimensions.  

Is it possible to store the details and calculations and have the form repeat (using different dimensions or selections)?

So if my form calculates the size of a box 33x23 (box 1), with a set of options and generates a cost for that.  I want to add (box 2) which is 12x40, which calculates the cost for box 2, then box 3, etc.  At the end, I need a list of the boxes and their options and a final cost for all 3 boxes.

I did a form similar to this in php storing the data in arrays, then calling up the arrays at the end.

Is this possible in Zigaform WP Cost Estimator?

**Comment by larangin** [comment]
I think you can do that. the logic calculation depends on you. here a tutorial how it works: https://www.youtube.com/watch?v=p9s_BV-nxLU
here some examples of complex forms: https://kb.softdiscover.com/docs/zigaform-wordpress-cost-estimator/examples/

**Comment by larangin** [comment]
since there is no response. this issue is closed
